language: node_js
node_js:
  - 8
  - 10
  - 12

env:
  - CXX=g++
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++

install:
  - npm install

script:
  - npm test

notifications:
  email:
    recipients:
      - sergak.shpak@gmail.com
    on_success: change
    on_failure: always
